package rules;
import grapheme.*;

//1

rule "Sukoon deletion rule"
    when
    //سكون
      $letter : Letter(content == "a")
    then
      $letter.setRepresentation(Letter.NULL_CHAR);
end

//2-1

rule "Elision First Rule(وا)"
    when
      $letter : Letter(content == "ا")
      eval($letter.nextIs("و"))
    then
      $letter.setRepresentation(Letter.NULL_CHAR);
end

//2-2

rule "Elision Second Rule( الف بعدها تنوين)"
    when
      $letter : Letter(content == "ا")
      //تنوين فتحة
      eval($letter.nextIs("a"))
    then
      $letter.setRepresentation(Letter.NULL_CHAR);
end

// 4 - 1
rule "Glottal Stop first"
    when
      $letter : Letter(content == "أ")
      eval($letter.getPrevious() == null)
    then
      $letter.setRepresentation("?a");
end

//2-3

rule "Elision Third Rule( همزة الوصل متل طأطأ)"
    when
      $letter : Letter(content == "أ")
    then
      $letter.setRepresentation("?");
end

//2-4

rule "Elision Fourth Rule(مد الألف متل جواب)"
    when
      $letter : Letter(content == "ا")
      // فتحة
      eval($letter.prevIs("a"))
    then
      $letter.setRepresentation("a:");
end

// 3

rule "Ya Maqsourah"
    when
      $letter : Letter(content == "ى")
    then
      $letter.setRepresentation("a");
end


// 4 - 2
rule "Glottal Stop second"
    when
      $letter : Letter(content == "ء")
    then
      $letter.setRepresentation("?a");
end

//5 - 1

rule "Tanween Fataha"
    when
    //تنوين فتحة
      $letter : Letter(content == "")
    then
      $letter.setRepresentation("an");
end

//5 - 2

rule "Tanween Dama"
    when
    //تنوين ضمة
      $letter : Letter(content == "aaa")
    then
      $letter.setRepresentation("un");
end

//5 - 3

rule "Tanween Kasra"
    when
    // تنوين كسرة
      $letter : Letter(content == "aaa")
    then
      $letter.setRepresentation("in");
end


// 6

rule "Shedaa or Gemination"
    when
     //شدة
      $letter : Letter(content == "")
    then
      $letter.setRepresentation(String.valueOf($letter.getPrevious().getRepresentation()));
end


// 7 - 1

rule "Ligature First"
    when
      $letter : Letter(content == "ؤ")
    then
      $letter.setRepresentation("?u");
end

// 7 - 2

rule "Ligature Second"
    when
      $letter : Letter(content == "ئ")
    then
      $letter.setRepresentation("?i");
end


// 7 - 3

rule "Ligature Third"
    when
      $letter : Letter(content == "أ")
    then
      $letter.setRepresentation("?a");
end

// 7 - 4

rule "Ligature Fourth"
    when
      $letter : Letter(content == "آ")
    then
      $letter.setRepresentation("?a:");
end

// 8 - 1

rule "Shamsi"
    when
      $letter : Letter(content == "ل")
      eval($letter.prevIs("ا"))
      eval($letter.getNext().isShamsi())
    then
      $letter.setRepresentation(Graphemes.getRepresentation(String.valueOf($letter.getNext().getContent())));
      $letter.getPrevious().setRepresentation("?a");
end

// 9 - 1

rule "Long vowel generation first"
    when
     // فتحة
      $letter : Letter(content == "aa")
      eval($letter.nextIs("ا"))
    then
      $letter.setRepresentation("a:");
end

// 9 - 2

rule "Long vowel generation second"
    when
     //ضمة
      $letter : Letter(content == "")
      eval($letter.nextIs("و"))
    then
      $letter.setRepresentation("u:");
end

// 9 - 3

rule "Long vowel generation third"
    when
    //كسرة
      $letter : Letter(content == "aaa")
      eval($letter.nextIs("ي"))
    then
      $letter.setRepresentation("i:");
end

// 11 - 1
rule "Fataha"
    when
    //فتحة
      $letter : Letter(content == "saa")
      eval(!$letter.nextIs("ا"))
    then
      $letter.setRepresentation("a:");
end

// 11 - 2
rule "Dama"
    when
    //ضمة
      $letter : Letter(content == "")
      eval(!$letter.nextIs("و"))
    then
      $letter.setRepresentation("w:");
end

// 11 - 3
rule "Kasra"
    when
    //كسرة
      $letter : Letter(content == "")
      eval(!$letter.nextIs("ي"))
    then
      $letter.setRepresentation("i:");
end
